### ISSUE TITLE
Xamarin Forms - Get Face Image fromPassports

### ISSUE THREAD

**Issue by wmtandrewz** [BlinkID/blinkid-xamarin#21]
Hi,

I'm trying to extract face image from passports using MRTD recognizer.
Full document image is extracted but unable to extract face image.
Appreciate anyone can help on this with code sample.

Thanks.

**Comment by jcular** [comment]
Hi @wmtandrewz,

MRTD recognizer can't return face image, but you can add both MRTD recognizer and DocumentFace recognizer at the same time and wait for them to be valid, just make sure you set [this property](https://github.com/BlinkID/blinkid-xamarin/blob/1bbfdcbde8b0645d5bf97f8c10849315bb72e7ce/Binding/Forms/BlinkID.Forms/BlinkID.Forms.iOS/Recognizers/RecognizerCollection.cs#L25) on recognizer collection to true. Otherwise only one will become valid.

Kind regards,
Jure
